// scripts/build-web.js — the static ARIA site for Firebase Hosting:
// `npm run build:web` (or `npm run deploy:web` to build and deploy).
//
// Copies public/ to dist-web/ and writes a site-config.js that turns on
// public/js/apiBase.js: the page has no server of its own there, so it uses
// your PC's desktop app when it answers and Render otherwise.
//   ARIA_CLOUD_URL  the Render server (default https://aria-69jr.onrender.com)
//   ARIA_PC_URL     the desktop app  (default http://127.0.0.1:3717)
// Both servers must list the site's origin in ARIA_WEB_ORIGINS, which by
// default includes personal-suite-aria.web.app (lib/auth.js).

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "public");
const OUT = path.join(ROOT, "dist-web");

const brains = [
  { label: "This PC", url: process.env.ARIA_PC_URL || "http://127.0.0.1:3717" },
  { label: "Cloud (Render)", url: process.env.ARIA_CLOUD_URL || "https://aria-69jr.onrender.com" },
];

fs.rmSync(OUT, { recursive: true, force: true });
fs.cpSync(SRC, OUT, {
  recursive: true,
  // Uploads belong to a server; the old stylesheet isn't linked anywhere.
  filter: (src) => !/[\\/]public[\\/](uploads|style-old\.css)/.test(src),
});

fs.writeFileSync(
  path.join(OUT, "js", "site-config.js"),
  `// Generated by scripts/build-web.js for the static site. See apiBase.js.
window.ARIA_SITE = ${JSON.stringify({ brains }, null, 2)};
`,
);

const files = fs.readdirSync(OUT, { recursive: true }).length;
console.log(`dist-web/ ready (${files} entries). Brains: ${brains.map((b) => `${b.label} ${b.url}`).join(", ")}`);
